{{- if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "streamingapp.fullname" . }}-mongodb
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  serviceName: {{ include "streamingapp.fullname" . }}-mongodb
  replicas: 1
  selector:
    matchLabels:
      {{- include "streamingapp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mongodb
  template:
    metadata:
      labels:
        {{- include "streamingapp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: data
          mountPath: /data/db
        resources:
          {{- toYaml .Values.mongodb.resources | nindent 12 }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.mongodb.persistence.storageClass }}
      resources:
        requests:
          storage: {{ .Values.mongodb.persistence.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "streamingapp.fullname" . }}-mongodb
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  ports:
  - port: 27017
    targetPort: mongodb
    protocol: TCP
    name: mongodb
  clusterIP: None
  selector:
    {{- include "streamingapp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
{{- end }}
