apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streamingapp.fullname" . }}-secrets
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  {{- if .Values.secrets.awsAccessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.awsSecretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.awsS3Bucket }}
  AWS_S3_BUCKET: {{ .Values.secrets.awsS3Bucket | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.awsCdnUrl }}
  AWS_CDN_URL: {{ .Values.secrets.awsCdnUrl | b64enc | quote }}
  {{- end }}
